# Generated by Django 4.2.7 on 2026-07-20 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0009_user_activity_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentassignment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discussionmessage',
            name='collaboration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mapapi.collaboration'),
        ),
    ]
